// <auto-generated />
using BlazorEcommerce.Server.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231008024139_changeImage")]
    partial class changeImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Striped Logo-Intarsia Cotton Track Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/30629810019746309/in/w560_q60.jpg",
                            Price = 9.99m,
                            Title = "GUCCI"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Webbing-Trimmed Logo-Print Stretch-Jersey Hooded Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/1647597301034878/in/w560_q60.jpg",
                            Price = 7.99m,
                            Title = "GUCCI"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Monogrammed Linen-Blend Suit Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/1647597311499279/in/w560_q60.jpg",
                            Price = 8.99m,
                            Title = "GUCCI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
