// <auto-generated />
using BlazorEcommerce.Server.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231007234714_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pain reliever and fever reducer",
                            ImageUrl = "https://media.istockphoto.com/id/458563393/photo/aspirin-bottle-with-tablets-spilling-out.jpg?s=612x612&w=0&k=20&c=MuRtWxOfp_rA2hWvVxAoJEeOcaWFIQ1xqtieh-W5iG8=",
                            Price = 9.99m,
                            Title = "Aspirin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nonsteroidal anti-inflammatory drug (NSAID)",
                            ImageUrl = "https://m.media-amazon.com/images/I/71byBwaWpuL._AC_UF894,1000_QL80_.jpg",
                            Price = 7.99m,
                            Title = "Ibuprofen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Antibiotic used to treat bacterial infections",
                            ImageUrl = "https://www.mintrxpharmacy.com/on/demandware.static/-/Sites-master-catalog/default/dwec20c7c0/images/products/amoxicillin_capsule_500.jpg",
                            Price = 8.99m,
                            Title = "Amoxicillin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
