// <auto-generated />
using BlazorEcommerce.Server.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jeans",
                            Url = "Jeans"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jackets",
                            Url = "Jackets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes",
                            Url = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "T-Shirts",
                            Url = "T-Shirts"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dresses",
                            Url = "Dresses"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hats",
                            Url = "Hats"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessories",
                            Url = "Accessories"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Striped Logo-Intarsia Cotton Track Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/30629810019746309/in/w560_q60.jpg",
                            Price = 9.99m,
                            Title = "GUCCI"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Webbing-Trimmed Logo-Print Stretch-Jersey Hooded Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/1647597301034878/in/w560_q60.jpg",
                            Price = 7.99m,
                            Title = "GUCCI"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Monogrammed Linen-Blend Suit Jacket",
                            ImageUrl = "https://www.mrporter.com/variants/images/1647597311499279/in/w560_q60.jpg",
                            Price = 8.99m,
                            Title = "GUCCI"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Classic Blue Jeans",
                            ImageUrl = "https://denim.ua/image/cache/catalog/files/378194546_muzhskie-dzhinsy-levis-600x800.jpg",
                            Price = 49.99m,
                            Title = "Levi's Jeans"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Comfortable Running Shoes",
                            ImageUrl = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/f655b4fb-35e9-4a63-acf8-c02dfd78cfda/zoom-fly-5-road-running-shoes-lkx7Zp.png",
                            Price = 89.99m,
                            Title = "Nike Running Shoes"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Casual Cotton T-Shirt",
                            ImageUrl = "https://brand-centr.com/image/cache/catalog/2031121%20-1-1678366701-1500x1500.jpg",
                            Price = 19.99m,
                            Title = "Adidas T-Shirt"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Description = "Elegant Red Evening Dress",
                            ImageUrl = "https://media.istockphoto.com/id/1217970889/photo/beautiful-female-red-dress-without-sleeves-isolated-on-white-evening-dress.jpg?s=612x612&w=0&k=20&c=SV4eWKwIY-HsUkrCi6X2jApUBcC5-lKFSd_tKG5Ewcw=",
                            Price = 129.99m,
                            Title = "Red Dress"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Description = "Classic Fedora Hat",
                            ImageUrl = "https://m.media-amazon.com/images/I/71EzZPIe+oL._AC_UY1000_.jpg",
                            Price = 39.99m,
                            Title = "Fedora Hat"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Description = "Stylish Sunglasses",
                            ImageUrl = "https://assets.oakley.com/is/image/OakleyEYE/888392327031_holbrook_matte-black-prizm-sapphr-irid-polar_main_046.png?impolicy=SEO_4x3",
                            Price = 29.99m,
                            Title = "Sunglasses"
                        });
                });

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorEcommerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
